#ce fichier stocke les infos sensibles ou configurables : 
# Fichier de configuration (clés API, marques à suivre, dates)
[API_KEYS]
# Clé API pour accéder aux données financières (ex: Alpha Vantage, Yahoo Finance)
financial_data_api_key = VOTRE_CLE_API_ICI
# Clé API pour accéder aux données de tendances Google (ex: Google Trends API)
google_trends_api_key = VOTRE_CLE_API_ICI
[BRANDS]
# Liste des noms pour Google Trends (mots-clés de recherche)
google_keywords = Christian Dior, Louis Vuitton, Hermes, Prada, Gucci, Burberry, Ralph Lauren, Tommy Hilfiger, Calvin Klein

# Dictionnaire mapping Marque -> Ticker Boursier (Format JSON pour le parsing facile)
# Note : Pour les groupes (LVMH, Kering, PVH), on répète le ticker, sous forme de texte
stock_tickers = {"Christian Dior": "MC.PA", "Louis Vuitton": "MC.PA", "Hermes": "RMS.PA", "Prada": "1913.HK", "Gucci": "KER.PA", "Burberry": "BRBY.L", "Ralph Lauren": "RL", "Tommy Hilfiger": "PVH", "Calvin Klein": "PVH"}

#Dictionnaire de mapping des marques à leur FW associée 
brands_fw={"Christian Dior": "Paris", "Louis Vuitton": "Paris", "Hermes": "Paris", "Prada": "Milan", "Gucci": "Milan", "Burberry": "London", "Ralph Lauren": "New York", "Tommy Hilfiger": "New York", "Calvin Klein": "New York"}

[DATES]
start_date = 2020-01-01
end_date = 2023-12-31

[FASHION_WEEKS]
# Format: ville_saison = start_date, end_date
# SS = Spring/Summer (présentée en automne de l'année précédente)
# AW = Autumn/Winter (présentée au printemps de l'année en cours)

#Paris
paris_ss20 = 2019-09-23, 2019-10-01
paris_aw20 = 2020-02-24, 2020-03-04
paris_ss21 = 2020-09-28, 2020-10-06
paris_aw21 = 2021-03-01, 2021-03-09
paris_ss22 = 2021-09-27, 2021-10-05
paris_aw22 = 2022-02-28, 2022-03-08
paris_ss23 = 2022-09-26, 2022-10-04
paris_aw23 = 2023-02-27, 2023-03-07

#Milan
milan_ss20 = 2019-09-17, 2019-09-23
milan_aw20 = 2020-02-18, 2020-02-24
milan_ss21 = 2020-09-22, 2020-09-28
milan_aw21 = 2021-02-23, 2021-03-01
milan_ss22 = 2021-09-21, 2021-09-27
milan_aw22 = 2022-02-22, 2022-02-28
milan_ss23 = 2022-09-20, 2022-09-26
milan_aw23 = 2023-02-21, 2023-02-27

#London
london_ss20 = 2019-09-13, 2019-09-17
london_aw20 = 2020-02-14, 2020-02-18
london_ss21 = 2020-09-17, 2020-09-22
london_aw21 = 2021-02-19, 2021-02-23
london_ss22 = 2021-09-17, 2021-09-21
london_aw22 = 2022-02-18, 2022-02-22
london_ss23 = 2022-09-16, 2022-09-20
london_aw23 = 2023-02-17, 2023-02-21

#NNew_York
new_york_ss20 = 2019-09-06, 2019-09-12
new_york_aw20 = 2020-02-07, 2020-02-12
new_york_ss21 = 2020-09-13, 2020-09-16
new_york_aw21 = 2021-02-13, 2021-02-18
new_york_ss22 = 2021-09-08, 2021-09-15
new_york_aw22 = 2022-02-11, 2022-02-17
new_york_ss23 = 2022-09-09, 2022-09-14
new_york_aw23 = 2023-02-10, 2023-02-16

